### ISSUE TITLE
Can not able to exect code

### ISSUE THREAD

**Issue by gunahk** [lee212/sh2ansible#1]
Hi,

Nice to see code. I could not able to execute the code. I think  some packages are missing, May I know what packages to be install
Error is :

Traceback (most recent call last):
  File "sh2ansible.py", line 157, in <module>
    main()
  File "sh2ansible.py", line 154, in main
    sh2ansible.convert()
  File "sh2ansible.py", line 76, in convert
    linedict = Line(line)
  File "sh2ansible.py", line 94, in __init__
    self.parse()
  File "sh2ansible.py", line 99, in parse
    self.module()
  File "sh2ansible.py", line 116, in module
    self.module = module
UnboundLocalError: local variable 'module' referenced before assignment

**Comment by lee212** [comment]
It's broken, allow me to figure out how to fix.

**Comment by FireBurn** [comment]
Any updates with this?
